WIP:
  title:  "/WIP/i"
feature:
  title:  "/(feat|feature)/i"
bug:
  title:  /"(fix|bugfix|bug)"/i
docs:
  title:  "/docs/i"
chore:
  title:  /"chore"/ig
feature:
  title:  "/(feat|feature)/i"
Demo:
  title:  "/demo/i"
