name: Auto Merge Pull Requests

on: [pull_request,pull_request_review,status]

jobs:
  automerge:
    runs-on: ubuntu-18.04
    steps:
    - name: Merge pull requests
      uses: pascalgn/automerge-action@v0.4.2
      env: 
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_METHOD: "squash"
        LABELS: "!wip,!work in progress"

- name: Condition-based Pull Request labeler

on:
  - pull_request

jobs:
  build:

	runs-on: ubuntu-latest
	
	steps:
	- uses: srvaroa/labeler@v0.2
	  env:
		GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }
    