name: PR Labeler
on: 
  push:
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [edited, submitted]
  

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.2
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
