name: PR Labeler
on: 
  push:
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [edited, submitted]
  

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
