name: PR Labeler
on: [pull_request,pull_request_review,status]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
